steps:
  - name: 'gcr.io/paketo-buildpacks/pack'
    entrypoint: 'pack'
    args: ['build', 'gcr.io/$PROJECT_ID/ml-test-1', '--builder', 'gcr.io/buildpacks/builder:v1']
    env:
      - 'GOOGLE_ENTRYPOINT=gunicorn main:app'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'ml-test-1',
      '--image', 'gcr.io/$PROJECT_ID/ml-test-1',
      '--region', 'us-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - 'gcr.io/$PROJECT_ID/ml-test-1'
