steps:
  - name: 'gcr.io/buildpacks/builder'
    env:
      - 'GOOGLE_ENTRYPOINT=gunicorn main:app'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ml-test-1', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'ml-test-1',
      '--image', 'gcr.io/$PROJECT_ID/ml-test-1',
      '--region', 'us-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  
images:
  - 'gcr.io/$PROJECT_ID/ml-test-1'
